create table if not exists public.letters (
	id bigint generated by default as identity primary key,
	user_id uuid not null references public.users (id) on delete cascade,
	job_description text,
	cv_text text not null,
	letter text,
	status text not null default 'pending' check (status in ('pending', 'complete', 'error')),
	error text,
	created_at timestamptz not null default now()
);

alter table public.letters enable row level security;

create policy "Users can view their own letters"
	on public.letters for select
	using (auth.uid() = user_id);

create policy "Users can insert their own letters"
	on public.letters for insert
	with check (auth.uid() = user_id);

create policy "Users can update their own letters"
	on public.letters for update
	using (auth.uid() = user_id);
